# Generated by Django 5.0.2 on 2024-03-22 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='make',
            old_name='brand',
            new_name='brands',
        ),
    ]
