# Generated by Django 5.0.2 on 2024-03-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_brand_make_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='condition',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='price',
            field=models.IntegerField(default=1200000),
            preserve_default=False,
        ),
    ]
