# Generated by Django 5.0.2 on 2024-03-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_brands_condition_brands_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
