# Generated by Django 5.0.2 on 2024-03-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_brands_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
